# Generated by Django 3.0.8 on 2020-07-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findplace', '0002_auto_20200720_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objtype', models.CharField(choices=[('cafe', 'Cafe'), ('hospital', 'Hospital'), ('police', 'Police')], max_length=20)),
            ],
        ),
    ]
