# Generated by Django 3.0.8 on 2020-07-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findplace', '0004_auto_20200720_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objtype',
            name='objtype',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('hospital', 'Hospital'), ('police', 'Police')], max_length=20),
        ),
    ]
